version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
# Har disablet cooldown for denne applikasjonen - baseimaget 'pdfgenrs' utvikles av Nav, så risikoen bør være begrenset,
# og inntil https://github.com/dependabot/dependabot-core/issues/14611 blir løst, så funker ikke dependabot sammen med
# docker-image hostet på github packages.
#    cooldown:
#      default-days: 7
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all-minor-updates:
        update-types:
          - "minor"
          - "patch"
