apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pengeflyt-pdfgenrs
  namespace: oppgjorsrapporter
  labels:
    team: oppgjorsrapporter
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 100Mi
  accessPolicy:
    inbound:
      rules:
        - application: sokos-oppgjorsrapporter
