name: Deploy

env:
  TZ: Europe/Oslo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '.github/**'
  schedule:
    # Deploy den 3. i hver måned kl. 08.23 (så er vi innafor "bygg og deploy minst hver 3. måned"-etterlevelseskravet)
    - cron: "23 8 3 * *"

# Hvis denne workflowen trigges flere ganger i løpet av kort tid (f.eks. ved at multiple PRs merges kjapt etter
# hverandre), vil vi at kjøringene [N+1, ...] skal vente med å starte til kjøring N er ferdig.
# På denne måten kan vi være sikre på at dersom N+1 f.eks. inneholder en sikkerhetsfiks, så risikerer vi ikke at N
# bruker lang tid på dev-deploy, og så prod-deployes (uten fiksen) etter N+1.
# Settingen `cancel-in-progress: false` gjør at:
#  * Hvis jobb N+1 trigges mens N fortsatt kjører, blir *ikke* N avbrutt, men N+1 blir liggende i kø til N er ferdig
#  * Hvis jobb N+2 også trigges mens N fortsatt kjøres, fjernes N+1, og N+2 legges i kø
concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      actions: read
      checks: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Test
        run: ./gradlew test

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: oppgjorsrapporter
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.sha }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}


  deploy_to_dev:
    name: Deploy to dev
    needs: [build]
    permissions:
      contents: read
      id-token: write
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy_to_prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    needs: [build, deploy_to_dev]
    permissions:
      contents: read
      id-token: write
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
