name: Deploy

env:
  TZ: Europe/Oslo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '.github/**'
  schedule:
    # Deploy den 3. i hver måned kl. 08.23 (så er vi innafor "bygg og deploy minst hver 3. måned"-etterlevelseskravet)
    - cron: "23 8 3 * *"

jobs:
  build:
    permissions:
      contents: read
      actions: read
      checks: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: oppgjorsrapporter
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ github.sha }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}


  deploy_to_dev:
    name: Deploy to dev
    needs: [build]
    permissions:
      contents: read
      id-token: write
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy_to_prod:
    name: Deploy to prod
    if: github.ref == 'refs/heads/main'
    needs: [build, deploy_to_dev]
    permissions:
      contents: read
      id-token: write
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
