name: "Check for newer image versions"

env:
  TZ: Europe/Oslo

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 2"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: navikt/digestabot@3302a753e533ceb9ec216de7f78345436cd636e3 # v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: oppgjorsrapporter
